export interface IOlympicData {
    firstName:String,
      lastName:String,
      dob:Date,
      gender:Boolean,
      posAplyFor:String,
      empRef:String,
      mobNum:Number,
      homephNum:Number,
      officeNum:Number,
      perEmail:String,
      locality:String,
      city:String,
      pinCode:Number,
      district:String,
      state:String,
      country:String,
      landmark:String,
      possport:String,
      visa:String,
      maritalStatus:String,
      // famMumber:this.fb.group({
      //   name: [''],
      //   age: [''],
      //   relationship: [''],
      //   occOrOrg1: ['']
      // }),
      Language:String,
      speak:Boolean,
      write:Boolean,
      perAddress:String
  }